version: "3.8"

services:

  app:
    build: .
    entrypoint: bash /usr/src/app/entrypoint.sh
    command: ["mix", "run", "--no-halt"]
    depends_on:
      - localstack
    volumes:
      - .:/usr/src/app
    networks:
      vpcbr:

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    networks:
      vpcbr:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    environment:
      # see https://docs.localstack.cloud/user-guide/aws/kinesis/
      # - DEBUG=1
      - EDGE_PORT=80
      - LOCALSTACK_SERVICES=kinesis,iam,s3,ec2
      - LOCALSTACK_KINESIS_INITIALIZE_STREAMS=samplestream:1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      vpcbr:
        # overriding hardcoded amazon ip, as ExAws uses this ip hardcoded
        ipv4_address: 169.254.169.254

volumes:
  localstack:


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 169.254.169.0/24
         gateway: 169.254.169.1
